//! Integration adapters (Anti-Corruption Layer) for {{MODULE_NAME_PASCAL}} module
//!
//! Integration adapters translate between external module types and internal domain types.
//! They implement the Anti-Corruption Layer pattern from DDD.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Integration adapters will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target integration
