//! Repository traits for {{MODULE_NAME_PASCAL}} module
//!
//! This module defines repository interfaces for domain entities.
//! Implementations are in the infrastructure layer.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Repository traits will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target repository-trait
