// {{MODULE_NAME}} {{PascalCaseEntity}} CLI Presentation Layer
// Generated by Metaphor Framework CLI

pub mod {{entity_name_snake}}_commands;

// Re-export main CLI handler and types
pub use {{entity_name_snake}}_commands::{
    {{PascalCaseEntity}}Commands, {{PascalCaseEntity}}Action, {{PascalCaseEntity}}CliHandler
};