//! Application Layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - Services (application business logic)
//! - Use cases (Clean Architecture interactors)
//! - Commands (CQRS write operations)
//! - Queries (CQRS read operations)
//! - Middleware (auth & RBAC)
//! - Triggers (lifecycle hooks)
//! - Validation (input validation)
//! - Workflows (saga/orchestration patterns)
//! - Bulk operations (high-performance data processing)
//! - Event subscriptions (handle events from other modules)

pub mod service;
pub mod usecases;
pub mod commands;
pub mod queries;
pub mod middleware;
pub mod triggers;
pub mod validation;
pub mod workflows;
pub mod bulk_operations;
pub mod event_subscription;

// Re-exports will be added by schema generator
// pub use service::*;
// pub use usecases::*;
// pub use bulk_operations::*;
