//! Database Seeders for {{ModuleName}}
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Comprehensive seed data generation with programmatic data creation
//! including realistic scenarios and progress tracking.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;
use chrono::Utc;
use uuid::Uuid;

use super::Seeder;
use crate::domain::entity::{{EntityName}};

/// Seeder for {{EntityName}}
pub struct Seed{{EntityName}}Seeder;

impl Seed{{EntityName}}Seeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for Seed{{EntityName}}Seeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for Seed{{EntityName}}Seeder {
    fn name(&self) -> &'static str {
        "Seed{{EntityName}}Seeder"
    }

    fn order(&self) -> i32 {
        3 // Adjust based on dependency order
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if {{entity_name}} table has any data
        let count: (i64,) = sqlx::query_as(&format!("SELECT COUNT(*) FROM {{entity_name_plural}}"))
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        println!("🌱️  Seeding {{entity_name_plural}}...");

        // Create comprehensive {{entity_name}} seed data
        let {{entity_name_plural}} = self.generate_seed_{{entity_name_plural}}();

        let mut created_count = 0;
        let mut failed_count = 0;

        for {{entity_name}} in {{entity_name_plural}} {
            match self.create_{{entity_name}}(pool, &{{entity_name}}).await {
                Ok(_) => {
                    created_count += 1;
                    if created_count % 10 == 0 {
                        println!("   ✓ Created {} {{entity_name_plural}}", created_count);
                    }
                }
                Err(e) => {
                    failed_count += 1;
                    println!("   ❌ Failed to create {{entity_name}} {}: {}", {{entity_name}}.id, e);
                }
            }
        }

        println!("   ✅ {{EntityName}} seeding complete: {} created, {} failed", created_count, failed_count);

        // Run SQL seed files for any additional setup
        if let Ok(sql) = std::fs::read_to_string("migrations/seeds/{{seed_file_name}}.sql") {
            println!("   📄 Running additional {{entity_name}} SQL setup...");
            sqlx::raw_sql(sql).execute(pool).await?;
        }

        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        // Delete in reverse order due to foreign keys
        sqlx::query(&format!("DELETE FROM {{entity_name_plural}}"))
            .execute(pool)
            .await?;
        Ok(())
    }
}

// Helper functions for Seed{{EntityName}}Seeder (not part of the trait)
impl Seed{{EntityName}}Seeder {
    /// Create a {{entity_name}} in the database
    async fn create_{{entity_name}}(&self, pool: &PgPool, {{entity_name}}: &{{EntityName}}) -> Result<()> {
        let query = r#"
            INSERT INTO {{entity_name_plural}} (
                id, {{entity_fields}}, created_at, updated_at, metadata
            ) VALUES (
                $1, {{field_placeholders}}, $2, $3, $4
            )
            ON CONFLICT (id) DO NOTHING
        "#;

        sqlx::query(query)
            .bind({{entity_name}}.id)
            {{field_bindings}}
            .bind({{entity_name}}.created_at.unwrap_or_else(|| Utc::now()))
            .bind({{entity_name}}.updated_at.unwrap_or_else(|| Utc::now()))
            .bind(&{{entity_name}}.metadata)
            .execute(pool)
            .await?;

        Ok(())
    }

    /// Generate comprehensive seed {{entity_name}} data
    fn generate_seed_{{entity_name_plural}}(&self) -> Vec<{{EntityName}}> {
        let mut {{entity_name_plural}} = Vec::new();

        // 1. System/Administrative {{entity_name_plural}}
        // Generated based on entity schema and business requirements

        // 2. Test and development {{entity_name_plural}}
        // Generated for testing and development scenarios

        // 3. Demo {{entity_name_plural}} with different statuses
        // Generated to showcase various states and scenarios

        // 4. Additional demo {{entity_name_plural}} for testing
        // Generated for load testing and edge cases

        // Example pattern for {{EntityName}} generation:
        /*
        // System {{entity_name_plural}}
        {{entity_name_plural}}.push({{EntityName}} {
            id: Uuid::parse_str("00000000-0000-0000-0000-000000000001").unwrap(),
            {{entity_field_assignments}}
            created_at: Some(Utc::now()),
            updated_at: Some(Utc::now()),
            metadata: serde_json::json!({
                "is_system": true,
                "created_by": "seeder"
            }),
        });

        // Test {{entity_name_plural}}
        for i in 1..=10 {
            {{entity_name_plural}}.push({{EntityName}} {
                id: Uuid::new(),
                {{test_entity_field_assignments}}
                created_at: Some(Utc::now()),
                updated_at: Some(Utc::now()),
                metadata: serde_json::json!({
                    "is_test": true,
                    "test_index": i,
                    "created_by": "seeder"
                }),
            });
        }

        // Demo {{entity_name_plural}}
        for i in 1..=50 {
            {{entity_name_plural}}.push({{EntityName}} {
                id: Uuid::new(),
                {{demo_entity_field_assignments}}
                created_at: Some(Utc::now()),
                updated_at: Some(Utc::now()),
                metadata: serde_json::json!({
                    "is_demo": true,
                    "demo_index": i,
                    "created_by": "seeder"
                }),
            });
        }
        */

        // This will be generated by metaphor-schema based on the {{EntityName}} structure
        // and business rules defined in the schema

        todo!("Generate seed {{entity_name_plural}} implementation for {{EntityName}}")
    }

    /// Generate realistic field values based on field types
    fn generate_field_value(&self, field_name: &str, field_type: &str, index: usize) -> serde_json::Value {
        match field_type {
            "string" | "text" => {
                match field_name {
                    "name" | "title" => serde_json::json!(format!("Sample {{EntityName}} {}", index)),
                    "email" => serde_json::json!(format!("sample{}@demo.local", index)),
                    "description" => serde_json::json!(format!("Description for sample {{entity_name}} {}", index)),
                    "username" => serde_json::json!(format!("user{}", index)),
                    "status" => serde_json::json!(["active", "inactive", "pending"][index % 3]),
                    _ => serde_json::json!(format!("{} {}", field_name, index)),
                }
            }
            "number" | "integer" => serde_json::json!(index as i32),
            "float" | "decimal" => serde_json::json!(index as f64 + 0.5),
            "boolean" => serde_json::json!(index % 2 == 0),
            "date" | "datetime" => serde_json::json!(Utc::now().format("%Y-%m-%d").to_string()),
            "uuid" => serde_json::json!(Uuid::new_v4().to_string()),
            _ => serde_json::Value::Null,
        }
    }

    /// Create metadata for different {{entity_name}} types
    fn create_metadata(&self, {{entity_name}}_type: &str, index: usize) -> serde_json::Value {
        match {{entity_name}}_type {
            "system" => serde_json::json!({
                "is_system": true,
                "created_by": "seeder",
                "environment": "seed"
            }),
            "test" => serde_json::json!({
                "is_test": true,
                "test_index": index,
                "created_by": "seeder"
            }),
            "demo" => serde_json::json!({
                "is_demo": true,
                "demo_index": index,
                "created_by": "seeder"
            }),
            _ => serde_json::json!({
                "created_by": "seeder"
            }),
        }
    }
}