// {{PascalCaseEntity}} HTTP Handlers - Complete CRUD System
// Generated by Metaphor Framework CLI

use actix_web::{web, HttpResponse, Responder, Result as ActixResult};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::application::{
    ApplicationServices,
    Create{{PascalCaseEntity}}Command, Create{{PascalCaseEntity}}Response,
    Get{{PascalCaseEntity}}Query, Get{{PascalCaseEntity}}Response,
    Update{{PascalCaseEntity}}Command, Update{{PascalCaseEntity}}Response,
    Delete{{PascalCaseEntity}}Command, Delete{{PascalCaseEntity}}Response,
    List{{PascalCaseEntity}}Query, List{{PascalCaseEntity}}Response,
    BulkCreate{{PascalCaseEntity}}Command, BulkCreate{{PascalCaseEntity}}Response,
    Upsert{{PascalCaseEntity}}Command, Upsert{{PascalCaseEntity}}Response,
    Restore{{PascalCaseEntity}}Command, Restore{{PascalCaseEntity}}Response,
    EmptyTrashCommand, EmptyTrashResponse,
    {{PascalCaseEntity}}Dto, {{PascalCaseEntity}}Filters
};
use crate::domain::repositories::{PaginationParams, SortParams};

// HTTP Request DTOs
#[derive(Debug, Deserialize)]
pub struct Create{{PascalCaseEntity}}Request {
    // TODO: Add your fields here based on entity proto
    // Example: pub name: String;
    // Example: pub description: Option<String>;
    #[serde(flatten)]
    pub custom_fields: HashMap<String, serde_json::Value>,
}

impl From<Create{{PascalCaseEntity}}Request> for Create{{PascalCaseEntity}}Command {
    fn from(request: Create{{PascalCaseEntity}}Request) -> Self {
        Self {
            custom_fields: request.custom_fields,
            created_by: "system".to_string(), // This should come from authentication context
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct Update{{PascalCaseEntity}}Request {
    // TODO: Add your fields here based on entity proto
    // Example: pub name: Option<String>;
    // Example: pub description: Option<String>;
    #[serde(flatten)]
    pub custom_fields: HashMap<String, serde_json::Value>,
}

impl From<Update{{PascalCaseEntity}}Request> for Update{{PascalCaseEntity}}Command {
    fn from(request: Update{{PascalCaseEntity}}Request) -> Self {
        Self {
            custom_fields: request.custom_fields,
            updated_by: "system".to_string(), // This should come from authentication context
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct BulkCreate{{PascalCaseEntity}}Request {
    pub items: Vec<Create{{PascalCaseEntity}}Request>,
}

#[derive(Debug, Deserialize)]
pub struct Upsert{{PascalCaseEntity}}Request {
    pub id: String,
    // TODO: Add your fields here based on entity proto
    #[serde(flatten)]
    pub custom_fields: HashMap<String, serde_json::Value>,
}

impl From<Upsert{{PascalCaseEntity}}Request> for Upsert{{PascalCaseEntity}}Command {
    fn from(request: Upsert{{PascalCaseEntity}}Request) -> Self {
        Self {
            id: request.id,
            custom_fields: request.custom_fields,
            updated_by: "system".to_string(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct List{{PascalCaseEntity}}Request {
    pub page: Option<usize>,
    pub page_size: Option<usize>,
    pub sort_by: Option<String>,
    pub sort_direction: Option<String>,
    pub search: Option<String>,
    // TODO: Add filter fields here based on your entity
    // Example: pub status: Option<String>;
}

impl From<List{{PascalCaseEntity}}Request> for List{{PascalCaseEntity}}Query {
    fn from(request: List{{PascalCaseEntity}}Request) -> Self {
        let mut filters = None;

        // Create filters if search or other filters are provided
        if request.search.is_some() {
            let mut {{entity_name_snake}}_filters = {{PascalCaseEntity}}Filters::new();

            if let Some(search) = request.search {
                {{entity_name_snake}}_filters = {{entity_name_snake}}_filters.with_search(search);
            }

            // TODO: Add more filters based on your entity
            // if let Some(status) = request.status {
            //     {{entity_name_snake}}_filters = {{entity_name_snake}}_filters.with_status(status);
            // }

            filters = Some({{entity_name_snake}}_filters);
        }

        let mut query = Self::new()
            .with_pagination(
                request.page.unwrap_or(1),
                request.page_size.unwrap_or(20),
            );

        if let Some(sort_by) = request.sort_by {
            let sort_direction = request.sort_direction.unwrap_or("asc".to_string());
            query = query.with_sort(sort_by, sort_direction);
        }

        if let Some(filters) = filters {
            query = query.with_filters(filters);
        }

        query
    }
}

// HTTP Response DTOs
#[derive(Debug, Serialize)]
pub struct {{PascalCaseEntity}}ListResponse {
    pub data: Vec<{{PascalCaseEntity}}Dto>,
    pub pagination: PaginationInfo,
    pub filters: Option<AppliedFilters>,
}

#[derive(Debug, Serialize)]
pub struct PaginationInfo {
    pub page: usize,
    pub page_size: usize,
    pub total: u64,
    pub total_pages: usize,
    pub has_next: bool,
    pub has_previous: bool,
}

#[derive(Debug, Serialize)]
pub struct AppliedFilters {
    pub search: Option<String>,
    // TODO: Add filter fields here based on your entity
    // Example: pub status: Option<String>;
}

#[derive(Debug, Serialize)]
pub struct BulkCreateResponse {
    pub created: usize,
    pub failed: usize,
    pub items: Vec<{{PascalCaseEntity}}Dto>,
    pub errors: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct ApiError {
    pub error: String,
    pub message: String,
    pub details: Option<serde_json::Value>,
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

impl ApiError {
    pub fn new(error: String, message: String) -> Self {
        Self {
            error,
            message,
            details: None,
            timestamp: chrono::Utc::now(),
        }
    }

    pub fn with_details(mut self, details: serde_json::Value) -> Self {
        self.details = Some(details);
        self
    }
}

impl Responder for ApiError {
    fn respond_to(self, _req: &actix_web::HttpRequest) -> HttpResponse {
        HttpResponse::InternalServerError().json(self)
    }
}

// HTTP Handlers
pub struct {{PascalCaseEntity}}HttpHandler {
    services: ApplicationServices,
}

impl {{PascalCaseEntity}}HttpHandler {
    pub fn new(services: ApplicationServices) -> Self {
        Self { services }
    }

    // 1. Create a new {{PascalCaseEntity}}
    pub async fn create_{{entity_name_snake}}(
        &self,
        request: web::Json<Create{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let command = Create{{PascalCaseEntity}}Command::from(request.into_inner());

        let handler = self.services.create_{{entity_name_snake}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                if response.success {
                    Ok(HttpResponse::Created().json(response))
                } else {
                    Err(ApiError::new(
                        "CREATION_FAILED".to_string(),
                        response.message,
                    ).into())
                }
            }
            Err(e) => Err(ApiError::new(
                "COMMAND_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 2. Get a {{PascalCaseEntity}} by ID
    pub async fn get_{{entity_name_snake}}(
        &self,
        path: web::Path<String>,
    ) -> ActixResult<HttpResponse> {
        let query = Get{{PascalCaseEntity}}Query::new(path.into_inner());

        let handler = self.services.get_{{entity_name_snake}}_handler();

        match self.services.execute_query(query, handler).await {
            Ok(response) => {
                if response.success {
                    Ok(HttpResponse::Ok().json(response))
                } else {
                    Ok(HttpResponse::NotFound().json(response))
                }
            }
            Err(e) => Err(ApiError::new(
                "QUERY_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 3. List {{PascalCaseEntity}} with optional filters
    pub async fn list_{{entity_name_plural}}(
        &self,
        query: web::Query<List{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let list_query = List{{PascalCaseEntity}}Query::from(query.into_inner());

        let handler = self.services.list_{{entity_name_plural}}_handler();

        match self.services.execute_query(list_query, handler).await {
            Ok(response) => {
                let {{entity_name_snake}}_response = {{PascalCaseEntity}}ListResponse {
                    data: response.{{entity_name_plural}},
                    pagination: PaginationInfo {
                        page: response.page,
                        page_size: response.page_size,
                        total: response.total,
                        total_pages: response.total_pages,
                        has_next: response.has_next,
                        has_previous: response.has_previous,
                    },
                    filters: None, // TODO: Extract filters from query
                };

                Ok(HttpResponse::Ok().json({{entity_name_snake}}_response))
            }
            Err(e) => Err(ApiError::new(
                "QUERY_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 4. Full update of a {{PascalCaseEntity}}
    pub async fn update_{{entity_name_snake}}(
        &self,
        path: web::Path<String>,
        request: web::Json<Update{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let id = path.into_inner();
        let mut command = Update{{PascalCaseEntity}}Command::from(request.into_inner());
        command.id = id;

        let handler = self.services.update_{{entity_name_snake}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                if response.success {
                    Ok(HttpResponse::Ok().json(response))
                } else {
                    Ok(HttpResponse::NotFound().json(response))
                }
            }
            Err(e) => Err(ApiError::new(
                "COMMAND_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 5. Partial update of a {{PascalCaseEntity}} (same as full update for now)
    pub async fn partial_update_{{entity_name_snake}}(
        &self,
        path: web::Path<String>,
        request: web::Json<Update{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        // For now, use the same logic as full update
        // In a complete implementation, you might want to differentiate
        self.update_{{entity_name_snake}}(path, request).await
    }

    // 6. Soft delete a {{PascalCaseEntity}}
    pub async fn delete_{{entity_name_snake}}(
        &self,
        path: web::Path<String>,
    ) -> ActixResult<HttpResponse> {
        let id = path.into_inner();
        let command = Delete{{PascalCaseEntity}}Command::new(id);

        let handler = self.services.delete_{{entity_name_snake}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                if response.success {
                    Ok(HttpResponse::NoContent().finish())
                } else {
                    Ok(HttpResponse::NotFound().json(response))
                }
            }
            Err(e) => Err(ApiError::new(
                "COMMAND_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 7. Bulk create {{PascalCaseEntity}}
    pub async fn bulk_create_{{entity_name_plural}}(
        &self,
        request: web::Json<BulkCreate{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let commands: Vec<Create{{PascalCaseEntity}}Command> = request.items
            .into_iter()
            .map(|item| Create{{PascalCaseEntity}}Command::from(item))
            .collect();

        let command = BulkCreate{{PascalCaseEntity}}Command::new(commands);

        let handler = self.services.bulk_create_{{entity_name_plural}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                let bulk_response = BulkCreateResponse {
                    created: response.created_count,
                    failed: response.failed_count,
                    items: response.created_{{entity_name_plural}},
                    errors: response.errors,
                };
                Ok(HttpResponse::Created().json(bulk_response))
            }
            Err(e) => Err(ApiError::new(
                "BULK_CREATE_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 8. Upsert {{PascalCaseEntity}}
    pub async fn upsert_{{entity_name_snake}}(
        &self,
        request: web::Json<Upsert{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let command = Upsert{{PascalCaseEntity}}Command::from(request.into_inner());

        let handler = self.services.upsert_{{entity_name_snake}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                Ok(HttpResponse::Ok().json(response))
            }
            Err(e) => Err(ApiError::new(
                "UPSERT_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 9. List deleted {{PascalCaseEntity}} (trash)
    pub async fn list_deleted_{{entity_name_plural}}(
        &self,
        query: web::Query<List{{PascalCaseEntity}}Request>,
    ) -> ActixResult<HttpResponse> {
        let list_query = List{{PascalCaseEntity}}Query::from(query.into_inner());
        let handler = self.services.list_deleted_{{entity_name_plural}}_handler();

        match self.services.execute_query(list_query, handler).await {
            Ok(response) => {
                let {{entity_name_snake}}_response = {{PascalCaseEntity}}ListResponse {
                    data: response.{{entity_name_plural}},
                    pagination: PaginationInfo {
                        page: response.page,
                        page_size: response.page_size,
                        total: response.total,
                        total_pages: response.total_pages,
                        has_next: response.has_next,
                        has_previous: response.has_previous,
                    },
                    filters: None,
                };

                Ok(HttpResponse::Ok().json({{entity_name_snake}}_response))
            }
            Err(e) => Err(ApiError::new(
                "QUERY_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 10. Restore deleted {{PascalCaseEntity}}
    pub async fn restore_{{entity_name_snake}}(
        &self,
        path: web::Path<String>,
    ) -> ActixResult<HttpResponse> {
        let id = path.into_inner();
        let command = Restore{{PascalCaseEntity}}Command::new(id);

        let handler = self.services.restore_{{entity_name_snake}}_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                if response.success {
                    Ok(HttpResponse::Ok().json(response))
                } else {
                    Ok(HttpResponse::NotFound().json(response))
                }
            }
            Err(e) => Err(ApiError::new(
                "RESTORE_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }

    // 11. Empty trash for {{PascalCaseEntity}}
    pub async fn empty_{{entity_name_snake}}_trash(
        &self,
    ) -> ActixResult<HttpResponse> {
        let command = EmptyTrashCommand::new();

        let handler = self.services.empty_{{entity_name_snake}}_trash_handler();

        match self.services.execute_command(command, handler).await {
            Ok(response) => {
                Ok(HttpResponse::Ok().json(response))
            }
            Err(e) => Err(ApiError::new(
                "EMPTY_TRASH_ERROR".to_string(),
                e.to_string(),
            ).into()),
        }
    }
}

// Configure routes
pub fn configure_{{entity_name_snake}}_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/{{entity_name_plural}}")
            // Standard CRUD endpoints
            .route("", web::post().to(create_{{entity_name_snake}}))
            .route("", web::get().to(list_{{entity_name_plural}}))
            .route("/{id}", web::get().to(get_{{entity_name_snake}}))
            .route("/{id}", web::put().to(update_{{entity_name_snake}}))
            .route("/{id}", web::patch().to(partial_update_{{entity_name_snake}}))
            .route("/{id}", web::delete().to(delete_{{entity_name_snake}}))

            // Extended Metaphor endpoints
            .route("/bulk", web::post().to(bulk_create_{{entity_name_plural}}))
            .route("/upsert", web::post().to(upsert_{{entity_name_snake}}))
            .route("/trash", web::get().to(list_deleted_{{entity_name_plural}}))
            .route("/empty-trash", web::delete().to(empty_{{entity_name_snake}}_trash))
            .route("/{id}/restore", web::post().to(restore_{{entity_name_snake}})),
    );
}

// Actix-web handler functions
async fn create_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    request: web::Json<Create{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.create_{{entity_name_snake}}(request).await
}

async fn get_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    path: web::Path<String>,
) -> ActixResult<HttpResponse> {
    handler.get_{{entity_name_snake}}(path).await
}

async fn list_{{entity_name_plural}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    query: web::Query<List{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.list_{{entity_name_plural}}(query).await
}

async fn update_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    path: web::Path<String>,
    request: web::Json<Update{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.update_{{entity_name_snake}}(path, request).await
}

async fn partial_update_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    path: web::Path<String>,
    request: web::Json<Update{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.partial_update_{{entity_name_snake}}(path, request).await
}

async fn delete_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    path: web::Path<String>,
) -> ActixResult<HttpResponse> {
    handler.delete_{{entity_name_snake}}(path).await
}

async fn bulk_create_{{entity_name_plural}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    request: web::Json<BulkCreate{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.bulk_create_{{entity_name_plural}}(request).await
}

async fn upsert_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    request: web::Json<Upsert{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.upsert_{{entity_name_snake}}(request).await
}

async fn list_deleted_{{entity_name_plural}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    query: web::Query<List{{PascalCaseEntity}}Request>,
) -> ActixResult<HttpResponse> {
    handler.list_deleted_{{entity_name_plural}}(query).await
}

async fn restore_{{entity_name_snake}}(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
    path: web::Path<String>,
) -> ActixResult<HttpResponse> {
    handler.restore_{{entity_name_snake}}(path).await
}

async fn empty_{{entity_name_snake}}_trash(
    handler: web::Data<{{PascalCaseEntity}}HttpHandler>,
) -> ActixResult<HttpResponse> {
    handler.empty_{{entity_name_snake}}_trash().await
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix_web::{test, web, App};

    #[actix_web::test]
    async fn test_create_{{entity_name_snake}}_request_conversion() {
        let request = Create{{PascalCaseEntity}}Request {
            custom_fields: HashMap::new(),
        };

        let command = Create{{PascalCaseEntity}}Command::from(request);
        assert_eq!(command.created_by, "system");
    }

    #[actix_web::test]
    async fn test_{{entity_name_snake}}_handler_creation() {
        // This would normally use real ApplicationServices
        // For testing, we'll create a mock implementation
        // TODO: Add mock implementation here
    }
}