//! Public API exports for {{MODULE_NAME_PASCAL}} module
//!
//! This module defines the public API that other modules can depend on.
//! It includes type-safe IDs, DTOs, and public events.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Exports will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target export
