//! Query handlers for {{MODULE_NAME_PASCAL}} module
//!
//! Queries represent read operations that don't modify state.
//! Part of CQRS pattern implementation.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Queries will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target cqrs
