//! {{EVENT_NAME}} domain event
//!
//! This event is published when...
//! Generated by Metaphor CLI.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// {{EVENT_NAME}} event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {{EVENT_NAME}} {
    /// Unique event ID
    pub event_id: String,

    /// When the event occurred
    pub occurred_at: DateTime<Utc>,

    /// Related entity ID
    pub {{ENTITY_NAME_SNAKE}}_id: String,

    // Add more fields as needed
}

impl {{EVENT_NAME}} {
    /// Create a new {{EVENT_NAME}} event
    pub fn new({{ENTITY_NAME_SNAKE}}_id: String) -> Self {
        Self {
            event_id: uuid::Uuid::new_v4().to_string(),
            occurred_at: Utc::now(),
            {{ENTITY_NAME_SNAKE}}_id,
        }
    }

    /// Get the event type name
    pub fn event_type() -> &'static str {
        "{{EVENT_NAME}}"
    }
}

/// Event handler trait for {{EVENT_NAME}}
#[async_trait::async_trait]
pub trait {{EVENT_NAME}}Handler: Send + Sync {
    /// Handle the {{EVENT_NAME}} event
    async fn handle(&self, event: {{EVENT_NAME}}) -> anyhow::Result<()>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_{{EVENT_NAME_SNAKE}}_creation() {
        let event = {{EVENT_NAME}}::new("test-id".to_string());
        assert!(!event.event_id.is_empty());
        assert_eq!(event.{{ENTITY_NAME_SNAKE}}_id, "test-id");
    }
}
