//! {{MODULE_NAME_PASCAL}} Module
//!
//! This module will be generated by metaphor-schema. Run:
//! ```bash
//! metaphor schema generate {{MODULE_NAME}} --target all
//! ```
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - CLI commands with enhanced UX
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator
//! - Advanced bulk operations
//! - Programmatic database seeding

// Generated modules
pub mod config;
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// {{MODULE_NAME_PASCAL}} module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```rust,ignore
/// let module = {{MODULE_NAME_PASCAL}}Module::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// let router = module.routes();
/// ```
pub struct {{MODULE_NAME_PASCAL}}Module {
    db_pool: Arc<PgPool>,
    // Add your services here after running:
    // metaphor schema generate {{MODULE_NAME}} --target all
}

impl {{MODULE_NAME_PASCAL}}Module {
    /// Create a new module builder
    pub fn builder() -> {{MODULE_NAME_PASCAL}}ModuleBuilder {
        {{MODULE_NAME_PASCAL}}ModuleBuilder::new()
    }

    /// Configure HTTP routes for this module using Axum
    ///
    /// Returns an Axum Router with all 12 Metaphor CRUD endpoints per entity.
    pub fn routes(&self) -> Router {
        // Routes will be generated by metaphor schema generate
        // For now, return empty router
        Router::new()
    }
}

/// Builder for {{MODULE_NAME_PASCAL}}Module
pub struct {{MODULE_NAME_PASCAL}}ModuleBuilder {
    db_pool: Option<PgPool>,
}

impl {{MODULE_NAME_PASCAL}}ModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<{{MODULE_NAME_PASCAL}}Module> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        Ok({{MODULE_NAME_PASCAL}}Module {
            db_pool: Arc::new(db_pool),
        })
    }
}

impl Default for {{MODULE_NAME_PASCAL}}ModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
