//! {{COMMAND_NAME}} command
//!
//! This command handles the {{COMMAND_NAME}} operation for {{ENTITY_NAME}} entities.
//! Generated by Metaphor CLI.

use anyhow::Result;
use async_trait::async_trait;

/// {{COMMAND_NAME}} command
///
/// This command is used to {{COMMAND_DESCRIPTION}} a {{ENTITY_NAME}}.
#[derive(Debug, Clone)]
pub struct {{COMMAND_NAME}}Command {
    // Add command fields here
    // pub id: String,
    // pub name: String,
}

impl {{COMMAND_NAME}}Command {
    /// Create a new {{COMMAND_NAME}} command
    pub fn new(/* add parameters */) -> Self {
        Self {
            // Initialize fields
        }
    }
}

/// Command result
#[derive(Debug)]
pub struct {{COMMAND_NAME}}Result {
    pub success: bool,
    pub id: Option<String>,
    pub message: Option<String>,
}

/// {{COMMAND_NAME}} command handler
#[async_trait]
pub trait {{COMMAND_NAME}}Handler: Send + Sync {
    /// Execute the {{COMMAND_NAME}} command
    async fn handle(&self, command: {{COMMAND_NAME}}Command) -> Result<{{COMMAND_NAME}}Result>;
}

/// Default implementation of {{COMMAND_NAME}} handler
pub struct Default{{COMMAND_NAME}}Handler {
    // Add dependencies (repository, etc.)
}

impl Default{{COMMAND_NAME}}Handler {
    pub fn new(/* add dependencies */) -> Self {
        Self {
            // Initialize dependencies
        }
    }
}

#[async_trait]
impl {{COMMAND_NAME}}Handler for Default{{COMMAND_NAME}}Handler {
    async fn handle(&self, command: {{COMMAND_NAME}}Command) -> Result<{{COMMAND_NAME}}Result> {
        // Implement command logic here
        tracing::info!("Executing {{COMMAND_NAME}} command");

        // 1. Validate command
        // 2. Load aggregate (if needed)
        // 3. Execute domain logic
        // 4. Persist changes
        // 5. Publish events (if needed)

        Ok({{COMMAND_NAME}}Result {
            success: true,
            id: None,
            message: Some("Command executed successfully".to_string()),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_{{COMMAND_NAME_SNAKE}}_command() {
        // Add tests
        assert!(true);
    }
}
