//! Application Services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Services provide the business logic layer between handlers and repositories.

// Entity services will be generated here by metaphor-schema
