//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Entity handlers (Axum with MetaphorCrudHandler for 12 CRUD endpoints)
//! - API versioning (URL path, header, query param strategies)
//! - Route configuration

pub mod versioning;

// Entity handlers will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target handler
