//! Projections (CQRS read models) for {{MODULE_NAME_PASCAL}} module
//!
//! Projections are optimized read models built from domain events.
//! They provide query-specific views of the data.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Projections will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target projection
