//! Workflows
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Saga and orchestration patterns for complex business processes.

// Workflows will be generated here by metaphor-schema
