//! Command handlers for {{MODULE_NAME_PASCAL}} module
//!
//! Commands represent write operations that modify state.
//! Part of CQRS pattern implementation.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Commands will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target cqrs
