//! {{HANDLER_NAME}} HTTP handler
//!
//! Generated by Metaphor CLI.

use axum::{
    extract::State,
    response::IntoResponse,
    Json,
};
use serde::Serialize;
use std::sync::Arc;

pub type AppState = Arc<()>;

#[derive(Debug, Serialize)]
pub struct {{HANDLER_NAME}}Response {
    pub message: String,
}

pub async fn handle(
    State(state): State<AppState>,
) -> impl IntoResponse {
    Json({{HANDLER_NAME}}Response {
        message: "Hello from {{HANDLER_NAME}} handler".to_string(),
    })
}
