// {{MODULE_NAME}} {{PascalCaseEntity}} CRUD Application Layer
// Generated by Metaphor Framework CLI

// Public modules for commands and queries
pub mod commands;
pub mod queries;

// Application services coordination
pub mod {{entity_name_snake}}_services;

// Re-export main application service and types
pub use {{entity_name_snake}}_services::{{PascalCaseEntity}}ApplicationServices;

// Re-export commonly used types
pub use commands::{
    Create{{PascalCaseEntity}}Command, Create{{PascalCaseEntity}}Response,
    Update{{PascalCaseEntity}}Command, Update{{PascalCaseEntity}}Response,
    Delete{{PascalCaseEntity}}Command, Delete{{PascalCaseEntity}}Response,
    BulkCreate{{PascalCaseEntity}}Command, BulkCreate{{PascalCaseEntity}}Response,
    Upsert{{PascalCaseEntity}}Command, Upsert{{PascalCaseEntity}}Response,
    Restore{{PascalCaseEntity}}Command, Restore{{PascalCaseEntity}}Response,
    EmptyTrashCommand, EmptyTrashResponse,
    {{PascalCaseEntity}}Dto, {{PascalCaseEntity}}Filters,
};

pub use queries::{
    Get{{PascalCaseEntity}}Query, Get{{PascalCaseEntity}}Response,
    List{{PascalCaseEntity}}Query, List{{PascalCaseEntity}}Response,
    ListDeleted{{PascalCaseEntity}}Query,
};