//! gRPC services for {{MODULE_NAME_PASCAL}} module
//!
//! This module provides gRPC service implementations using Tonic.
//! Supports standard CRUD operations and streaming RPCs.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// gRPC services will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target grpc

// Feature-gated: requires "grpc" feature
// #[cfg(feature = "grpc")]
