//! Event store for {{MODULE_NAME_PASCAL}} module
//!
//! The event store persists domain events for event sourcing.
//! Includes event envelope, metadata, and snapshot support.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Event store implementations will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target event-store
