//! Presentation Layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - HTTP endpoints (REST API)
//! - DTOs (request/response structures)
//! - Versioning (API version routing)
//! - gRPC services (optional, feature-gated)
//! - CLI commands (command-line interface)

pub mod http;
pub mod dto;
pub mod versioning;
pub mod cli;

// gRPC support - feature-gated
#[cfg(feature = "grpc")]
pub mod grpc;

// Re-exports will be added by schema generator
// pub use dto::*;
