// {{MODULE_NAME}} {{PascalCaseEntity}} HTTP Presentation Layer
// Generated by Metaphor Framework CLI

pub mod handlers;

// Re-export HTTP handler types
pub use handlers::{{PascalCaseEntity}}HttpHandler;
pub use handlers::configure_{{entity_name_snake}}_routes;