//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses metaphor-orm's `DatabaseOperations<T>` trait.

// Entity repositories will be generated here by metaphor-schema

// Re-export metaphor-orm types
pub use metaphor_orm::repository::{
    DatabaseOperations, Entity, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};
