//! PostgreSQL implementation of {{ENTITY_NAME}} repository
//!
//! Generated by Metaphor CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use crate::domain::repository::{
    {{ENTITY_NAME}}Repository, PaginationParams, SortParams, PaginatedResult, {{ENTITY_NAME}},
};

/// PostgreSQL implementation of {{ENTITY_NAME}}Repository
pub struct Postgres{{ENTITY_NAME}}Repository {
    pool: PgPool,
}

impl Postgres{{ENTITY_NAME}}Repository {
    /// Create a new PostgreSQL repository
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl {{ENTITY_NAME}}Repository for Postgres{{ENTITY_NAME}}Repository {
    async fn save(&self, entity: &{{ENTITY_NAME}}) -> Result<()> {
        // Implement save logic
        // sqlx::query!(
        //     "INSERT INTO {{COLLECTION}} (id, ...) VALUES ($1, ...) ON CONFLICT (id) DO UPDATE SET ...",
        //     entity.id,
        // )
        // .execute(&self.pool)
        // .await?;
        Ok(())
    }

    async fn find_by_id(&self, id: &str) -> Result<Option<{{ENTITY_NAME}}>> {
        // Implement find by ID
        // let row = sqlx::query_as!(
        //     {{ENTITY_NAME}},
        //     "SELECT * FROM {{COLLECTION}} WHERE id = $1 AND deleted_at IS NULL",
        //     id
        // )
        // .fetch_optional(&self.pool)
        // .await?;
        Ok(None)
    }

    async fn find_all(
        &self,
        pagination: PaginationParams,
        sort: SortParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>> {
        // Implement pagination
        Ok(PaginatedResult {
            items: vec![],
            total: 0,
            page: pagination.page,
            per_page: pagination.per_page,
        })
    }

    async fn delete(&self, id: &str, hard: bool) -> Result<()> {
        if hard {
            // Hard delete
            // sqlx::query!("DELETE FROM {{COLLECTION}} WHERE id = $1", id)
        } else {
            // Soft delete
            // sqlx::query!("UPDATE {{COLLECTION}} SET deleted_at = NOW() WHERE id = $1", id)
        }
        Ok(())
    }

    async fn find_deleted(
        &self,
        pagination: PaginationParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>> {
        Ok(PaginatedResult {
            items: vec![],
            total: 0,
            page: pagination.page,
            per_page: pagination.per_page,
        })
    }

    async fn restore(&self, id: &str) -> Result<()> {
        // sqlx::query!("UPDATE {{COLLECTION}} SET deleted_at = NULL WHERE id = $1", id)
        Ok(())
    }

    async fn count(&self) -> Result<u64> {
        // let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM {{COLLECTION}} WHERE deleted_at IS NULL")
        //     .fetch_one(&self.pool)
        //     .await?;
        Ok(0)
    }

    async fn search(
        &self,
        query: &str,
        pagination: PaginationParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>> {
        // Implement full-text search
        Ok(PaginatedResult {
            items: vec![],
            total: 0,
            page: pagination.page,
            per_page: pagination.per_page,
        })
    }
}
