//! {{ENTITY_NAME}} repository interface
//!
//! This module defines the repository interface for {{ENTITY_NAME}} entities.
//! Generated by Metaphor CLI.

use anyhow::Result;
use async_trait::async_trait;

// Import entity types
// use crate::domain::entity::{{ENTITY_NAME}};

/// Pagination parameters
#[derive(Debug, Clone, Default)]
pub struct PaginationParams {
    pub page: u32,
    pub per_page: u32,
}

/// Sort parameters
#[derive(Debug, Clone, Default)]
pub struct SortParams {
    pub field: String,
    pub direction: SortDirection,
}

/// Sort direction
#[derive(Debug, Clone, Default)]
pub enum SortDirection {
    #[default]
    Ascending,
    Descending,
}

/// Paginated result
#[derive(Debug)]
pub struct PaginatedResult<T> {
    pub items: Vec<T>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// {{ENTITY_NAME}} repository interface
///
/// This trait defines the contract for {{ENTITY_NAME}} persistence operations.
#[async_trait]
pub trait {{ENTITY_NAME}}Repository: Send + Sync {
    /// Save an entity (create or update)
    async fn save(&self, entity: &{{ENTITY_NAME}}) -> Result<()>;

    /// Find an entity by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<{{ENTITY_NAME}}>>;

    /// Find all entities with pagination
    async fn find_all(
        &self,
        pagination: PaginationParams,
        sort: SortParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>>;

    /// Delete an entity (soft or hard)
    async fn delete(&self, id: &str, hard: bool) -> Result<()>;

    /// Find deleted entities
    async fn find_deleted(
        &self,
        pagination: PaginationParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>>;

    /// Restore a soft-deleted entity
    async fn restore(&self, id: &str) -> Result<()>;

    /// Count entities
    async fn count(&self) -> Result<u64>;

    /// Search entities
    async fn search(
        &self,
        query: &str,
        pagination: PaginationParams,
    ) -> Result<PaginatedResult<{{ENTITY_NAME}}>>;
}

// Type alias for the entity - replace with actual type when available
pub type {{ENTITY_NAME}} = ();
