//! Permission Definitions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! RBAC permission constants for each entity and action.

// Permission definitions will be generated here by metaphor-schema
