//! Business rule specifications for {{MODULE_NAME_PASCAL}} module
//!
//! Specifications encapsulate business rules that can be combined
//! using logical operators (and, or, not) for complex queries.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Specifications will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target specification
