// CRUD Queries for {{PascalCaseEntity}}
// Generated by Metaphor Framework CLI

pub mod get_{{entity_name_snake}};
pub mod list_{{entity_name_plural}};

// Re-export commonly used types
pub use get_{{entity_name_snake}}::{
    Get{{PascalCaseEntity}}Query,
    Get{{PascalCaseEntity}}Response,
};

pub use list_{{entity_name_plural}}::{
    List{{PascalCaseEntity}}Query,
    List{{PascalCaseEntity}}Response,
    ListDeleted{{PascalCaseEntity}}Query,
};