//! State Machines
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Finite state machine definitions for entity lifecycle management.

// State machines will be generated here by metaphor-schema
