//! Computed Fields
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Derived fields computed from other entity properties.

use anyhow::Result;
use serde_json::{json, Value};
use std::collections::HashMap;
use chrono::Utc;
use super::entity::{{EntityName}};

/// Computed field values container
#[derive(Debug, Clone)]
pub struct ComputedFieldValues {
    pub fields: HashMap<String, Value>,
}

impl ComputedFieldValues {
    pub fn new() -> Self {
        Self {
            fields: HashMap::new(),
        }
    }

    pub fn set(&mut self, key: &str, value: Value) {
        self.fields.insert(key.to_string(), value);
    }

    pub fn get(&self, key: &str) -> Option<&Value> {
        self.fields.get(key)
    }
}

/// Trait for entities that have computed fields
pub trait HasComputedFields {
    fn computed_fields(&self) -> ComputedFieldValues;
}

// Computed field implementations will be generated here by metaphor-schema
// Example implementation for {{EntityName}}:

/*
impl HasComputedFields for {{EntityName}} {
    fn computed_fields(&self) -> ComputedFieldValues {
        let mut fields = ComputedFieldValues::new();
        let now = Utc::now();

        // Example computed fields (will be generated based on entity schema):
        // fields.set("is_active", json!(self.status == "active"));
        // fields.set("days_since_creation", json!(now.signed_duration_since(self.created_at).num_days()));
        // fields.set("display_name", json!(format!("{} {}", self.first_name, self.last_name)));

        fields
    }
}
*/
