//! Event subscriptions for {{MODULE_NAME_PASCAL}} module
//!
//! Event subscriptions handle domain events from other modules.
//! They implement the EventHandler trait for incoming events.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Event subscriptions will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target event-subscription
