// {{MODULE_NAME}} {{PascalCaseEntity}} Presentation Layer
// Generated by Metaphor Framework CLI

// HTTP presentation layer
pub mod http;

// gRPC presentation layer
pub mod grpc;

// CLI presentation layer
pub mod cli;

// Re-export main handlers and configuration functions
pub use http::{
    {{PascalCaseEntity}}HttpHandler,
    configure_{{entity_name_snake}}_routes,
};

pub use grpc::{{PascalCaseEntity}}GrpcService;

pub use cli::{
    {{PascalCaseEntity}}Commands, {{PascalCaseEntity}}Action, {{PascalCaseEntity}}CliHandler
};