//! API versioning for {{MODULE_NAME_PASCAL}} module
//!
//! Provides version-aware routing and version negotiation middleware.
//! Supports URL path, header, and query parameter versioning strategies.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// API versioning will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target versioning
