// {{MODULE_NAME}} {{PascalCaseEntity}} gRPC Presentation Layer
// Generated by Metaphor Framework CLI

pub mod services;

// Re-export main gRPC service and types
pub use services::{{PascalCaseEntity}}GrpcService;