//! Domain services for {{MODULE_NAME_PASCAL}} module
//!
//! Domain services encapsulate business logic that doesn't naturally
//! fit within a single entity. They operate on domain concepts.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Domain services will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target domain-service
