//! Domain Layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - Entities (domain objects with business logic)
//! - Repository traits (interfaces for persistence)
//! - Domain services (business logic across entities)
//! - Value objects (immutable domain objects)
//! - Specifications (composable business rules)
//! - State machines (entity lifecycle management)
//! - Events (domain events for integration)
//! - Permissions (authorization rules)
//! - Computed fields (derived field calculations)
//! - Exports (public API for other modules)

pub mod entity;
pub mod repositories;
pub mod services;
pub mod value_objects;
pub mod specifications;
pub mod state_machine;
pub mod event;
pub mod permission;
pub mod computed;
pub mod export;

// Re-exports will be added by schema generator
// pub use entity::*;
// pub use state_machine::*;
// pub use computed::*;
// pub use export::*;
