//! Data Transfer Objects (DTOs) for {{MODULE_NAME_PASCAL}} module
//!
//! DTOs define the request/response structures for the API layer.
//! Includes validation annotations and OpenAPI schema support.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// DTOs will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target dto

// Common types
// pub use common::{ApiResponse, ApiError, PaginationParams};
