//! Use cases for {{MODULE_NAME_PASCAL}} module
//!
//! Use cases represent application-specific business rules (Clean Architecture).
//! Each use case has Input/Output types and encapsulates a single operation.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Use cases will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target usecase
