// CRUD Commands for {{PascalCaseEntity}}
// Generated by Metaphor Framework CLI

pub mod create_{{entity_name_snake}};
pub mod update_{{entity_name_snake}};
pub mod delete_{{entity_name_snake}};
pub mod bulk_create_{{entity_name_plural}};
pub mod upsert_{{entity_name_snake}};
pub mod restore_{{entity_name_snake}};
pub mod empty_trash;

// Re-export commonly used types
pub use create_{{entity_name_snake}}::{
    Create{{PascalCaseEntity}}Command,
    Create{{PascalCaseEntity}}Response,
    {{PascalCaseEntity}}Dto,
};

pub use update_{{entity_name_snake}}::{
    Update{{PascalCaseEntity}}Command,
    Update{{PascalCaseEntity}}Response,
};

pub use delete_{{entity_name_snake}}::{
    Delete{{PascalCaseEntity}}Command,
    Delete{{PascalCaseEntity}}Response,
};

pub use bulk_create_{{entity_name_plural}}::{
    BulkCreate{{PascalCaseEntity}}Command,
    BulkCreate{{PascalCaseEntity}}Response,
};

pub use upsert_{{entity_name_snake}}::{
    Upsert{{PascalCaseEntity}}Command,
    Upsert{{PascalCaseEntity}}Response,
};

pub use restore_{{entity_name_snake}}::{
    Restore{{PascalCaseEntity}}Command,
    Restore{{PascalCaseEntity}}Response,
};

pub use empty_trash::{
    EmptyTrashCommand,
    EmptyTrashResponse,
};

// Additional response types for complex operations
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {{PascalCaseEntity}}Filters {
    pub search: Option<String>,
    // TODO: Add filter fields based on your entity
    // Example: pub status: Option<String>;
}

impl {{PascalCaseEntity}}Filters {
    pub fn new() -> Self {
        Self {
            search: None,
        }
    }

    pub fn with_search(mut self, search: String) -> Self {
        self.search = Some(search);
        self
    }

    // TODO: Add more filter methods based on your entity
    // pub fn with_status(mut self, status: String) -> Self {
    //     self.status = Some(status);
    //     self
    // }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {{PascalCaseEntity}}ListDto {
    pub {{entity_name_plural}}: Vec<{{PascalCaseEntity}}Dto>,
    pub page: usize,
    pub page_size: usize,
    pub total: u64,
    pub total_pages: usize,
    pub has_next: bool,
    pub has_previous: bool,
}

impl {{PascalCaseEntity}}ListDto {
    pub fn new(
        {{entity_name_plural}}: Vec<{{PascalCaseEntity}}Dto>,
        page: usize,
        page_size: usize,
        total: u64,
    ) -> Self {
        let total_pages = ((total as f64) / (page_size as f64)).ceil() as usize;

        Self {
            {{entity_name_plural}},
            page,
            page_size,
            total,
            total_pages,
            has_next: page < total_pages,
            has_previous: page > 1,
        }
    }
}