//! {{SERVICE_NAME}} domain service
//!
//! This service encapsulates domain logic that doesn't naturally fit
//! in an entity or value object.
//! Generated by Metaphor CLI.

use anyhow::Result;
use async_trait::async_trait;

/// {{SERVICE_NAME}} domain service trait
///
/// This trait defines the contract for {{SERVICE_DESCRIPTION}} operations.
#[async_trait]
pub trait {{SERVICE_NAME}}: Send + Sync {
    /// Example service method
    async fn process(&self, input: &str) -> Result<String>;
}

/// Default implementation of {{SERVICE_NAME}}
pub struct Default{{SERVICE_NAME}} {
    // Add dependencies here
}

impl Default{{SERVICE_NAME}} {
    /// Create a new instance
    pub fn new() -> Self {
        Self {}
    }
}

impl Default for Default{{SERVICE_NAME}} {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl {{SERVICE_NAME}} for Default{{SERVICE_NAME}} {
    async fn process(&self, input: &str) -> Result<String> {
        // Implement domain logic here
        tracing::info!("{{SERVICE_NAME}} processing: {}", input);

        Ok(format!("Processed: {}", input))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_{{SERVICE_NAME_SNAKE}}_process() {
        let service = Default{{SERVICE_NAME}}::new();
        let result = service.process("test").await.unwrap();
        assert!(result.contains("test"));
    }
}
