//! Value objects for {{MODULE_NAME_PASCAL}} module
//!
//! Value objects are immutable domain objects defined by their attributes
//! rather than identity. They include validation and business rules.
//!
//! Generated by metaphor-schema. Custom code sections are preserved.

// Value objects will be generated here by metaphor-schema
// Use: metaphor schema generate {{MODULE_NAME}} --target value-object
