//! {{SPEC_NAME}} specification
//!
//! A specification encapsulates a business rule that can be composed
//! and reused across the domain.
//! Generated by Metaphor CLI.

/// {{SPEC_NAME}} specification
///
/// This specification checks whether...
#[derive(Debug, Clone, Default)]
pub struct {{SPEC_NAME}} {
    // Add specification parameters here
}

impl {{SPEC_NAME}} {
    /// Create a new {{SPEC_NAME}} specification
    pub fn new() -> Self {
        Self::default()
    }

    /// Check if the candidate satisfies this specification
    pub fn is_satisfied_by<T>(&self, candidate: &T) -> bool
    where
        T: {{SPEC_NAME}}Candidate,
    {
        candidate.satisfies_{{SPEC_NAME_SNAKE}}()
    }
}

/// Trait for candidates that can be checked against {{SPEC_NAME}}
pub trait {{SPEC_NAME}}Candidate {
    /// Check if this candidate satisfies the {{SPEC_NAME}} specification
    fn satisfies_{{SPEC_NAME_SNAKE}}(&self) -> bool;
}

// Composite specification support

/// Combine two specifications with AND logic
pub struct AndSpecification<A, B> {
    left: A,
    right: B,
}

impl<A, B> AndSpecification<A, B> {
    pub fn new(left: A, right: B) -> Self {
        Self { left, right }
    }
}

/// Combine two specifications with OR logic
pub struct OrSpecification<A, B> {
    left: A,
    right: B,
}

impl<A, B> OrSpecification<A, B> {
    pub fn new(left: A, right: B) -> Self {
        Self { left, right }
    }
}

/// Negate a specification
pub struct NotSpecification<S> {
    inner: S,
}

impl<S> NotSpecification<S> {
    pub fn new(inner: S) -> Self {
        Self { inner }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Example candidate for testing
    struct TestCandidate {
        valid: bool,
    }

    impl {{SPEC_NAME}}Candidate for TestCandidate {
        fn satisfies_{{SPEC_NAME_SNAKE}}(&self) -> bool {
            self.valid
        }
    }

    #[test]
    fn test_{{SPEC_NAME_SNAKE}}_satisfied() {
        let spec = {{SPEC_NAME}}::new();
        let candidate = TestCandidate { valid: true };
        assert!(spec.is_satisfied_by(&candidate));
    }

    #[test]
    fn test_{{SPEC_NAME_SNAKE}}_not_satisfied() {
        let spec = {{SPEC_NAME}}::new();
        let candidate = TestCandidate { valid: false };
        assert!(!spec.is_satisfied_by(&candidate));
    }
}
