//! Triggers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Lifecycle hooks: before_create, after_create, before_update, etc.

use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use super::super::domain::entity::{{EntityName}};

/// Trigger context for {{EntityName}} operations
#[derive(Debug, Clone)]
pub struct {{EntityName}}TriggerContext {
    pub entity: {{EntityName}},
    pub operation: TriggerOperation,
    pub metadata: HashMap<String, serde_json::Value>,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub user_id: Option<String>,
}

impl {{EntityName}}TriggerContext {
    pub fn new(
        entity: {{EntityName}},
        operation: TriggerOperation,
        user_id: Option<String>,
    ) -> Self {
        Self {
            entity,
            operation,
            metadata: HashMap::new(),
            timestamp: chrono::Utc::now(),
            user_id,
        }
    }
}

/// Trigger operation types
#[derive(Debug, Clone, PartialEq)]
pub enum TriggerOperation {
    Create,
    Update,
    Delete,
    Restore,
    Archive,
}

/// Base trait for all triggers
#[async_trait]
pub trait Trigger {
    type Entity;

    async fn handle(&self, ctx: &TriggerContext<Self::Entity>) -> Result<()>;

    fn name(&self) -> &'static str;
    fn priority(&self) -> i32 { 0 } // Higher numbers = higher priority
}

/// Generic trigger context
pub struct TriggerContext<T> {
    pub entity: T,
    pub operation: TriggerOperation,
    pub metadata: HashMap<String, serde_json::Value>,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub user_id: Option<String>,
}

// Trigger implementations will be generated here by metaphor-schema
// Example pattern:

/*
#[async_trait]
impl Trigger for {{EntityName}}AfterCreateHandler1 {
    type Entity = {{EntityName}};

    async fn handle(&self, ctx: &TriggerContext<Self::Entity>) -> Result<()> {
        tracing::info!(
            "{{EntityName}}AfterCreateHandler1: Processing {} creation for entity_id: {}, operation: {:?}",
            stringify!({{EntityName}}).to_lowercase(),
            ctx.entity.id,
            ctx.operation
        );

        // Enhanced business logic will be generated here
        // - Logging and audit trails
        // - Notification systems
        // - Data validation and enrichment
        // - Cross-module integration

        Ok(())
    }

    fn name(&self) -> &'static str {
        "{{EntityName}}AfterCreateHandler1"
    }

    fn priority(&self) -> i32 {
        10 // High priority for logging
    }
}
*/
