//! {{VALUE_OBJECT_NAME}} value object
//!
//! A value object that represents...
//! Generated by Metaphor CLI.

use anyhow::{anyhow, Result};
use std::fmt;

/// {{VALUE_OBJECT_NAME}} value object
///
/// This is an immutable value object. Two instances are equal
/// if all their attributes are equal.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct {{VALUE_OBJECT_NAME}}(String);

impl {{VALUE_OBJECT_NAME}} {
    /// Create a new {{VALUE_OBJECT_NAME}} from a string value
    ///
    /// # Errors
    ///
    /// Returns an error if the value is invalid.
    pub fn new(value: &str) -> Result<Self> {
        let trimmed = value.trim();

        if trimmed.is_empty() {
            return Err(anyhow!("{{VALUE_OBJECT_NAME}} cannot be empty"));
        }

        // Add more validation rules here
        // Example: length check, format validation, etc.

        Ok(Self(trimmed.to_string()))
    }

    /// Get the inner value
    pub fn value(&self) -> &str {
        &self.0
    }

    /// Consume and return the inner value
    pub fn into_inner(self) -> String {
        self.0
    }
}

impl fmt::Display for {{VALUE_OBJECT_NAME}} {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl TryFrom<String> for {{VALUE_OBJECT_NAME}} {
    type Error = anyhow::Error;

    fn try_from(value: String) -> Result<Self> {
        Self::new(&value)
    }
}

impl TryFrom<&str> for {{VALUE_OBJECT_NAME}} {
    type Error = anyhow::Error;

    fn try_from(value: &str) -> Result<Self> {
        Self::new(value)
    }
}

impl From<{{VALUE_OBJECT_NAME}}> for String {
    fn from(vo: {{VALUE_OBJECT_NAME}}) -> Self {
        vo.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_{{VALUE_OBJECT_NAME_SNAKE}}_valid() {
        let vo = {{VALUE_OBJECT_NAME}}::new("valid value").unwrap();
        assert_eq!(vo.value(), "valid value");
    }

    #[test]
    fn test_{{VALUE_OBJECT_NAME_SNAKE}}_empty_fails() {
        let result = {{VALUE_OBJECT_NAME}}::new("");
        assert!(result.is_err());
    }

    #[test]
    fn test_{{VALUE_OBJECT_NAME_SNAKE}}_whitespace_trimmed() {
        let vo = {{VALUE_OBJECT_NAME}}::new("  trimmed  ").unwrap();
        assert_eq!(vo.value(), "trimmed");
    }

    #[test]
    fn test_{{VALUE_OBJECT_NAME_SNAKE}}_equality() {
        let vo1 = {{VALUE_OBJECT_NAME}}::new("same").unwrap();
        let vo2 = {{VALUE_OBJECT_NAME}}::new("same").unwrap();
        assert_eq!(vo1, vo2);
    }
}
