//! Infrastructure Layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - Persistence (repository implementations)
//! - Projections (CQRS read models)
//! - Event store (event sourcing storage)
//! - Integration (anti-corruption layer adapters)

pub mod persistence;
pub mod projections;
pub mod event_store;
pub mod integration;

// Re-exports will be added by schema generator
// pub use persistence::*;
